services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=kotlin_jooq_flyway'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5432:5432'
    volumes:
      - 'D:/volume:/var/lib/postgres/data postgres'